# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- dev

pool:
  #agent: 'uat-emr-com-sg-01'
  vmImage: 'ubuntu-latest'

steps:
- script: 
    npm install
  displayName: 'npm install'
- script: 
   npm install core-js -g && export NODE_OPTIONS="--no-warnings --max-old-space-size=2048" && npm run build
    #set NODE_OPTIONS=--max_old_space_size=8192 & npm run build
  displayName: 'npm build'
- task: S3Upload@1
  inputs:
    awsCredentials: 'semr2-dev-deployment'
    regionName: 'ap-southeast-1'
    bucketName: 'semr2-frontend-dev'
    sourceFolder: './dist'
    globExpressions: '**'