# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger: none

pool:
  name: 'SEMRGen2'

variables:
  #override the npm_config_cache environment variable to the custom path
  npm_config_cache: $(Build.SourcesDirectory)/node_modules 

steps:
- task: Cache@2
  inputs:
    key: 'version5 | npm | "$(Agent.OS)" | package.json'
    restoreKeys: |
      version5 | npm | "$(Agent.OS)"
    path: $(npm_config_cache)
    cacheHitVar: CACHE_RESTORED
  displayName: Cache npm    
        
- script: npm install
  condition: ne(variables.CACHE_RESTORED, 'true')
  displayName: 'npm install'
- script: 
    #export NODE_OPTIONS="--no-warnings --max-old-space-size=2048" && npm run build
    set NODE_OPTIONS=--max_old_space_size=8192 & npm run build
  displayName: 'npm build'
